name: canidrink
description: A flutter app for study purposes

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^3.0.1
  cupertino_icons: ^0.1.2
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true